#!/bin/sh
# Generate a firehose rawprogram0.xml that writes the Nerves images raw into
# LUN 0 of the Tachyon UFS via EDL (Particle CLI: `particle flash --tachyon
# prog_firehose_ddr.elf rawprogram0-nerves.xml`, which wraps Particle's
# qdl fork). Intended as the initial-install path before the device has
# networking for `mix upload`.
#
# Only LUN 0 sectors inside the Nerves area (p11-p15, carved from stock
# system_a) are ever written; the GPT itself and LUN1-6 are not touched, so
# the partition table must already be the Nerves layout (README.md sgdisk
# commands / support/phase2-install.sh). Sector numbers are 4096-byte UFS
# LBAs and mirror fwup_include/fwup-common.conf (512-byte offsets / 8).
#
# Usage: gen-rawprogram0.sh <images-dir> [out.xml]
#   <images-dir> must contain uboot-env.bin, Image, qcm6490-tachyon.dtb and
#   rootfs.squashfs (e.g. the firmware's unpacked resources or a system
#   artifact's images/ dir). Filenames in the XML are relative, so run
#   particle flash from that directory.
set -eu

IMAGES=${1:?images dir}
OUT=${2:-rawprogram0-nerves.xml}
SECTOR=4096

# 4K LBAs, see fwup-common.conf
UBOOT_ENV_LBA=1198848   # 0x124B00, p11
KERNEL_A_LBA=1199104    # 0x124C00, p12 slot A kernel (60 MiB area)
DTB_A_LBA=1214464       # 0x128800, p12 slot A DTB (4 MiB area)
ROOTFS_A_LBA=1231872    # p13
ROOTFS_B_LBA=1362944    # p14
APP_LBA=1494016         # p15

KERNEL_AREA_SECTORS=15360
DTB_AREA_SECTORS=1024
ROOTFS_SECTORS=131072   # 512 MiB

sectors() {
    size=$(wc -c < "$1")
    echo $(( (size + SECTOR - 1) / SECTOR ))
}

check_fits() {
    [ "$2" -le "$3" ] || { echo "$1 needs $2 sectors, slot is $3" >&2; exit 1; }
}

ENV_S=$(sectors "$IMAGES/uboot-env.bin");        check_fits uboot-env.bin "$ENV_S" 32
KERNEL_S=$(sectors "$IMAGES/Image");             check_fits Image "$KERNEL_S" $KERNEL_AREA_SECTORS
DTB_S=$(sectors "$IMAGES/qcm6490-tachyon.dtb");  check_fits dtb "$DTB_S" $DTB_AREA_SECTORS
ROOTFS_S=$(sectors "$IMAGES/rootfs.squashfs");   check_fits rootfs "$ROOTFS_S" $ROOTFS_SECTORS

# 128 KiB of 0xff used to invalidate the B rootfs and app data heads, the
# same thing fwup's complete task does with raw_memset(..., 256, 0xff).
INVALIDATE="$IMAGES/ff-128k.bin"
[ -f "$INVALIDATE" ] || { dd if=/dev/zero bs=131072 count=1 2>/dev/null | tr '\0' '\377' > "$INVALIDATE"; }

program() {
    # label start_sector num_sectors filename
    printf '  <program SECTOR_SIZE_IN_BYTES="%s" file_sector_offset="0" filename="%s" label="%s" num_partition_sectors="%s" physical_partition_number="0" start_sector="%s" />\n' \
        "$SECTOR" "$4" "$1" "$3" "$2"
}

{
    echo '<?xml version="1.0" ?>'
    echo '<data>'
    echo '  <!-- Nerves initial install: LUN 0, Nerves area only (p11-p15). Generated by support/edl/gen-rawprogram0.sh -->'
    program uboot_env  $UBOOT_ENV_LBA "$ENV_S"    uboot-env.bin
    program kernel_a   $KERNEL_A_LBA  "$KERNEL_S" Image
    program dtb_a      $DTB_A_LBA     "$DTB_S"    qcm6490-tachyon.dtb
    program rootfs_a   $ROOTFS_A_LBA  "$ROOTFS_S" rootfs.squashfs
    program rootfs_b_invalidate $ROOTFS_B_LBA 32 ff-128k.bin
    program data_invalidate     $APP_LBA      32 ff-128k.bin
    echo '</data>'
} > "$OUT"

echo "wrote $OUT (env $ENV_S, kernel $KERNEL_S, dtb $DTB_S, rootfs $ROOTFS_S sectors)"
